#include <Rcpp.h>
#include <algorithm>
using namespace Rcpp;
// [[Rcpp::plugins(cpp11)]]
//' Count positive and negative tests
//'
//' This function counts the positive and negative tests in the simulated
//' data generated by \code{run_forward_simulations()}.
//'
//' @param rho_1 the test sensitivity in the absence of antibiotics.
//'
//' @param rho_2 the test sensitivity in the presence of antibiotics.
//'
//' @param colonisations a vector of colonisation times of the patients.
//'
//' @param antibiotics a matrix where each row corresponds to a patient
//' and the entries correspond to a day when antibiotics were administered.
//'
//' @param days_of_tests a matrix where each row corresponds to a patient
//' and the entries correspond to a day when a test was conducted.
//'
//' @param n_patients the total number of patients.
//'
//' @return This function returns a vector with two elements. The first number
//' is the total number of positive tests, the second number is the total
//' number of negative tests.
//'
//' @export
// [[Rcpp::export]]
NumericVector count_tests_forward_simulations(double rho_1,
                                              double rho_2,
                                              NumericVector colonisations,
                                              NumericMatrix antibiotics,
                                              NumericMatrix days_of_tests,
                                              int n_patients) {


  NumericVector test_results;
  int positive_tests = 0;
  int negative_tests = 0;
  int n_col = days_of_tests.ncol();
  int day;
  NumericVector days_of_tests_pt;
  NumericVector antibiotics_pt;

  for (int pt = 0; pt < n_patients; pt++){


    days_of_tests_pt = days_of_tests(pt,_);
    antibiotics_pt = antibiotics(pt,_);

    for (int col = 0; col < n_col; col++){
      day = days_of_tests_pt(col);
      if (day != 0){

        // check if patient was positive on day
        if (colonisations(pt) < day){
          // check if patient was on antibiotics on day
          if (std::count(antibiotics_pt.begin(), antibiotics_pt.end(), day) == 0){
            // positive patients not on antibiotics get a positive result
            // with probability rho_1 and a negative result with probability
            // 1 - rho_1
            if (R::runif(0,1) < rho_1){
              positive_tests++;
            } else{
              negative_tests++;
            }

          } else {
            // positive patients on antibioitcs get a positive results
            // wiht probability rho_2 and a negative result with probability
            // 1 - rho_2
            if (R::runif(0,1) < rho_2){
              positive_tests++;
            } else{
              negative_tests++;
            }
          }

        } else {
          // negative patients get a negative result with probability 1
          negative_tests++;
        }
      }
    }
  }


  test_results.push_back(positive_tests);
  test_results.push_back(negative_tests);
  return(test_results);
}
