double log_lik_overall(Rcpp::NumericVector,
                     Rcpp::NumericVector,
                     Rcpp::NumericVector,
                     Rcpp::StringVector,
                     int,
                     int,
                     Rcpp::NumericMatrix,
                     Rcpp::NumericMatrix,
                     double,
                     double,
                     double,
                     double,
                     double,
                     int,
                              int);
