double log_lik_sources(int,
                       Rcpp::NumericVector,
                       Rcpp::NumericVector,
                       Rcpp::NumericVector,
                       Rcpp::NumericVector,
                       Rcpp::StringVector,
                       Rcpp::NumericVector,
                       Rcpp::NumericVector,
                       Rcpp::NumericVector,
                       int,
                       Rcpp::NumericMatrix,
                       double);
